all:
  hosts:
    frontend:
      ansible_host: 51.44.221.76
      ansible_user: ubuntu
      ansible_ssh_private_key_file: ~/.ssh/my-terraform-key
    backend:
      ansible_host: 15.237.28.37
      ansible_user: ubuntu
      ansible_ssh_private_key_file: ~/.ssh/my-terraform-key
    database:
      ansible_host: 172.31.12.174
      ansible_user: ubuntu
      ansible_ssh_private_key_file: ~/.ssh/my-terraform-key
      
  children:
    frontend_group:
      hosts:
        frontend:
    backend_group:
      hosts:
        backend:
    database_group:
      hosts:
        database: